openapi: 3.1.0
info:
  title: TODO Plugin
  description: A plugin that allows the user to analysis his hand in paili format
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /mahjong_paili/{hand}:
    get:
      operationId: getPaili
      summary: Get the shanten analysis of a hand 
      parameters:
      - in: path
        name: hand
        schema:
          type: string
        required: true
        description: The hand to analysis
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getPailiResponse'

components:
  schemas:
    getPailiResponse:
      type: object
      properties:
        paili:
          type: array
          items:
            type: object
            description: The analysis of a hand in paili format.
            properties:
              discard: 
                type: string
                description: which tile to discard
              shanten:
                type: int
                description: the shanten number after discarding the tile
              advance:
                type: array
                description: which tiles can help make an advance of the hand after drawing
                items:
                  type: string
                  description: tiles to draw
              advance_num:
                type: int
                description: number of tiles that can help make an advance of the hand
              good_shape_advance:
                type: array
                description: which tiles can help make a good-shape advance of the hand
                items:
                  type: string
                  description: tiles to draw
              good_shape_advance_num:
                type: int
                description: number of tiles that can help make a good-shape advance
              AI_recommendation:
                type: float
                description: AI recommendation for the next move, value from 0 to 1 and is normalized across the hand, larger means better
